module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['💗', '✨', '💜', '👻', '📍', '🔰', '💫', '🍂', '🌟', '🌚', '⚜️', '⭕', '🧿', '📌', '🍁', '〽️', '⚰️', '💎', '💜', '💙', '🌍', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/If2IrHuqGzTDyMD9HuTMRt?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/wz2uji.jpg',
    NEWSLETTER_JID: '@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'DG WHATSAPP BOT 〽️',
    OWNER_NAME: 'DASUN ⚡',
    OWNER_NUMBER: '94779885727',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ✨ DEVELOPED BY DG PROGRAMMER',
    CHANNEL_LINK: '',
};
